"""Add stations table

Revision ID: 7bdc26477cc5
Revises: 4315e4c42d60
Create Date: 2026-08-01 00:41:32.870805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdc26477cc5'
down_revision = '4315e4c42d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('grid_square', sa.String(length=8), nullable=True),
    sa.Column('primary_rig', sa.String(length=100), nullable=True),
    sa.Column('primary_antenna', sa.String(length=150), nullable=True),
    sa.Column('license_class', sa.String(length=30), nullable=True),
    sa.Column('dxcc_entity', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_user_id'))

    op.drop_table('stations')
    # ### end Alembic commands ###
