"""add clock settings

Revision ID: acf8fd0eaaaf
Revises: 7bdc26477cc5
Create Date: 2026-08-02 17:53:47.699756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf8fd0eaaaf'
down_revision = '7bdc26477cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clock_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('units', sa.String(length=20), nullable=False),
    sa.Column('map_projection', sa.String(length=30), nullable=False),
    sa.Column('show_satellites', sa.Boolean(), nullable=False),
    sa.Column('show_dx_cluster', sa.Boolean(), nullable=False),
    sa.Column('show_weather', sa.Boolean(), nullable=False),
    sa.Column('show_moon', sa.Boolean(), nullable=False),
    sa.Column('show_grayline', sa.Boolean(), nullable=False),
    sa.Column('default_zoom', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clock_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clock_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clock_settings_user_id'))

    op.drop_table('clock_settings')
    # ### end Alembic commands ###
