"""Add callsign lookup cache

Revision ID: ce34aa62aadf
Revises: 7bdc26477cc5
Create Date: 2026-08-01 02:03:07.742168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce34aa62aadf'
down_revision = '7bdc26477cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callsign_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('grid_square', sa.String(length=8), nullable=True),
    sa.Column('dxcc_entity', sa.String(length=100), nullable=True),
    sa.Column('cq_zone', sa.Integer(), nullable=True),
    sa.Column('itu_zone', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('looked_up_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_response_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('callsign_lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callsign_lookups_callsign'), ['callsign'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callsign_lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callsign_lookups_callsign'))

    op.drop_table('callsign_lookups')
    # ### end Alembic commands ###
